### ISSUE TITLE
TCGA-LUAD and TCGA-LUSC datasets' labels

### ISSUE THREAD

**Issue by RuixiangZhao** [GeorgeBatch/TCGA_lung#1]
Hi,

How did you get the labels of slide images in these two datasets？

Is there any information about slide image's labels in https://portal.gdc.cancer.gov/projects/TCGA-LUAD and https://portal.gdc.cancer.gov/projects/TCGA-LUSC?

**Comment by GeorgeBatch** [comment]
Hi,

From what I've seen, people usually use LUAD and LUSC as labels. LUAD is Lung Adenocarcinoma, LUSC is Lung Squamous Cell Carcinoma. Since they are 2 different types of lung cancer, you can think of a classification task of classifying lung-cancer images into these 2 types. As far as I understand, these 2 are the most common types. There are other types of lung cancer, so if you get a new slide, it is not necessary for it to be in one of these 2 classes.

I hope it helps. Let me know if you have any further questions.

**Comment by RuixiangZhao** [comment]
Thank you for your reply, which answered my doubts.
